I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/assets/scenes/party.rpy", line 89, in script
    $ renpy.pause(3.0, hard=true)
  File "game/assets/scenes/party.rpy", line 89, in <module>
    $ renpy.pause(3.0, hard=true)
NameError: name 'true' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/assets/scenes/party.rpy", line 89, in script
    $ renpy.pause(3.0, hard=true)
  File "C:\Users\Donobuz\Downloads\renpy-7.4.8-sdk/renpy/ast.py", line 923, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Donobuz\Downloads\renpy-7.4.8-sdk/renpy/python.py", line 2235, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/assets/scenes/party.rpy", line 89, in <module>
    $ renpy.pause(3.0, hard=true)
NameError: name 'true' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.8.1895
RoughDraft 1.0
Fri Oct  1 04:20:39 2021
